from django.urls import path,include
from . import views
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('base',views.base,name='base'),
  path('', views.home, name='home'),
  path('dashboard',views.dashboard,name='dashboard'),
  path('appointment',views.appointment,name='appointment'),
  path('addDoctorForm',views.addDoctorForm,name='addDoctorForm'),
  path('addDoctor',views.addDoctor,name='addDoctor'),
  path('addAppointment',views.addAppointment,name="addAppointment"),
  path('addTherapist',views.addTherapist,name="addTherapist"),
  path('Therapists',views.Therapists,name="Therapists"),
  path('patient',views.patient,name="patient"),
  path('signin',views.signin,name="signin"),
  path('forgotpwd',views.forgotpwd,name="forgotpwd"),
  path('getpwd',views.getpwd,name='getpwd'),
  path('addAdmin',views.addAdmin,name="addAdmin"),
  path('login',views.login,name="login"),
  path('header',views.header,name="header"),
  path('header1',views.header1,name="header1"),
  path('viewTherapist',views.viewTherapist,name="viewTherapist"),
  path('editpatientform/<int:id>',views.editpatientform,name='editpatient'),
  path('deletePatient/<int:id>',views.deletePatient,name="deletePatient"),
  path('editpatient',views.editpatient,name='editpatient'),
  path('bookingview',views.bookingview,name="bookingview"),
  path('deleteBooking/<int:id>',views.deleteBooking,name="deleteBooking"),
  path('editbookingform/<int:id>',views.editbookingform,name='editbookingform'),
  path('editbooking',views.editbooking,name='editbooking'),
  path('schedules',views.schedules,name='schedules'),
  path('doctorprofile/<int:id>',views.doctorprofile,name="doctorprofile"),
  path('therapistprofile/<int:id>',views.therapistprofile,name='therapistprofile'),
  path('edittherapist',views.edittherapist,name="edittherapist"),
  path('addScheduling',views.addScheduling,name="addScheduling"),
  path('listschedules',views.listschedules,name="listschedules"),
  path('editschedulingform/<int:id>',views.editschedulingform,name="editschedulingform"),
  path('editschedule',views.editschedule,name="editschedule"),
  path('deleteSchedule/<int:id>',views.deleteSchedule,name="deleteSchedule"),
  path('viewDoctor',views.viewDoctor,name="viewDoctor"),
  path('editdoctor',views.editdoctor,name="editdoctor"),
  path('searchpatient',views.searchpatient,name="searchpatient"),
  path('numbersessionsearch',views.numbersessionsearch,name="numbersessionsearch"),
  path('searchdoctorpatient',views.searchdoctorpatient,name="searchdoctorpatient"),
  path('searchbooking',views.searchbooking,name="searchbooking") ,
  path('searchschedule',views.searchschedule,name="searchschedule") ,
  path('patientprofile/<int:id>',views.patientprofile,name='patientprofile'),
  path('calendar',views.calendar,name="calendar"),
  path('random_color',views.random_color,name="random_color"),
  path('book',views.book,name='book'),
  path('update_schedule/',views.update_schedule,name='update_schedule'),
  path('therapy',views.therapy,name="therapy"),
  path('delete_therapy/<int:id>/', views.delete_therapy, name='delete_therapy'),
  path('doctorpatient',views.doctorpatient,name='doctorpatient'),
  path('editpatientreportform/<int:id>',views.editpatientreportform,name='editpatientreportform'),
  path('casesheet/<int:id>',views.casesheets,name='casesheet'),
  path('case/<int:id>',views.case,name='case'),
  path('addpatientreportform',views.addpatientreportform,name='addpatientreportform'),
  path('consultedpatient',views.consultedpatient,name='consultedpatient'),
  path('report',views.report,name='report'),
  path('update_schedules/',views.update_schedules,name='update_schedules'),
  path('department',views.department,name="department"),
  path('delete_department/<int:id>/', views.delete_department, name='delete_department'),
  path('edit_department/<int:id>/', views.edit_department, name='edit_department'),
  path('treatment', views.treatment, name='treatment'),
  path('delete_treatment/<int:id>/', views.delete_treatment, name='delete_treatment'),
  path('edit_treatment/<int:id>/', views.edit_treatment, name='edit_treatment'),
  path('status/', views.status, name='status'),
  path('statuss/', views.statuss, name='statuss'),
  path('deletestatus/<int:id>/',views.deletestatus, name='deletestatus'),
  path('deletestatuss/<int:id>/',views.deletestatuss, name='deletestatuss'),
  path('patient/<int:patient_id>/', views.patient_profile, name='patient_profile'),
  path('adminprofile',views.adminprofile,name='adminprofile'),
  path('changepwd',views.changepwd,name='changepwd'),
  path('editadmin',views.editadmin,name='editadmin'),
  path('passwordchange',views.passwordchange,name='passwordchange'),
  path('doctorchangepwd',views.doctorchangepwd,name='doctorchangepwd'),
  path('docprofile',views.docprofile,name='docprofile'),
  path('doctordashboard',views.doctordashboard,name='doctordashboard'),
  path('deleteTherapist/<int:id>/',views.deleteTherapist,name='deleteTherapist'),
  path('deleteDoctor/<int:id>/',views.deleteDoctor,name='deleteDoctor'),
  path('history/<int:id>/',views.history,name='history'),
  path('sessions/<int:schedule_id>/', views.view_sessions, name='view_sessions'),
  path('toggle-session-status/<int:session_id>/', views.toggle_session_status, name='toggle_session_status'),
  path('get_patient_details/', views.get_patient_details, name='get_patient_details'),
  path('numbersession',views.numbersession,name='numbersession'),
  path('update-session/<int:session_id>/', views.update_session, name='update_session'),
  path('importform',views.importform,name='importform'),
  path('upload_excel',views.upload_excel,name='upload_excel'),
  path('export-patients/', views.export_patients_to_excel, name='export_patients_to_excel'),
  path('edittherapy/<int:id>/', views.edittherapy, name='edittherapy'),
  path('create-consultations', views.create_consultations, name='create_consultations'),





] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)