# Generated by Django 4.0.6 on 2024-09-02 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0002_alter_patient_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='reg_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='reg_time',
            field=models.TimeField(null=True),
        ),
    ]
