# Generated by Django 4.0.6 on 2024-09-04 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0003_alter_booking_reg_date_alter_booking_reg_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='email',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
