# Generated by Django 4.0.6 on 2024-09-17 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0004_alter_patient_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statusbooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Status', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='sessionstatus',
            name='status',
            field=models.CharField(choices=[('not confirmed', 'Not Confirmed'), ('attended', 'Attended')], default='not confirmed', max_length=50),
        ),
    ]
