# Generated by Django 4.0.6 on 2024-09-18 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0007_alter_booking_status_alter_patient_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='Diagnosis',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='Examinationfindings',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
