# Generated by Django 4.0.6 on 2024-09-18 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0008_patient_diagnosis_patient_examinationfindings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='Allergies',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='Clinicaldetails',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='Diagnosis',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='Digestion',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='Examinationfindings',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='Historyofpresentingcomplaints',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='Menstrualhistory',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='PastMedicalandsurgicalhistory',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='Presentingcomplaints',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='Proposedtreatmentplan',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='Regularmedications',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='Sleep',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
