# Generated by Django 4.0.6 on 2024-09-20 04:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0009_alter_patient_allergies_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consultation_date', models.DateTimeField(auto_now_add=True)),
                ('medicines', models.TextField(null=True)),
                ('number_of_session', models.CharField(max_length=50, null=True)),
                ('Followup', models.CharField(max_length=100, null=True)),
                ('Proposedtreatmentplan', models.CharField(max_length=100, null=True)),
                ('Treatment', models.CharField(max_length=100, null=True)),
                ('Srothusinvolved', models.CharField(max_length=100, null=True)),
                ('Dhathupredominence', models.CharField(max_length=100, null=True)),
                ('Doshapredominence', models.CharField(max_length=100, null=True)),
                ('Amanirama', models.CharField(max_length=100, null=True)),
                ('Regularmedications', models.CharField(max_length=500, null=True)),
                ('PastMedicalandsurgicalhistory', models.CharField(max_length=500, null=True)),
                ('Historyofpresentingcomplaints', models.CharField(max_length=500, null=True)),
                ('Presentingcomplaints', models.CharField(max_length=500, null=True)),
                ('Menstrualhistory', models.CharField(max_length=500, null=True)),
                ('Allergies', models.CharField(max_length=100, null=True)),
                ('Sleep', models.CharField(max_length=100, null=True)),
                ('Digestion', models.CharField(max_length=100, null=True)),
                ('Clinicaldetails', models.CharField(max_length=500, null=True)),
                ('update_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('Examinationfindings', models.CharField(max_length=500, null=True)),
                ('Diagnosis', models.CharField(max_length=100, null=True)),
                ('Booking', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Booking.booking')),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Booking.doctor')),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='Booking.patient')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Booking.statusbooking')),
            ],
        ),
    ]
