# Generated by Django 4.0.6 on 2024-09-20 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0010_consultation'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='therapy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Booking.therapy'),
        ),
    ]
